### ISSUE TITLE
missing patchSampler

### ISSUE THREAD

**Issue by jingyanw** [albanie/mcnFasterRCNN#1]
Hi,

Is the file for patchSampler https://github.com/albanie/mcnFasterRCNN/blob/c980c8ae032eec803c92475b1dc78c207b5cb4a6/core/faster_rcnn_train_get_batch.m#L91 missing in the repo? Thanks!

**Comment by jingyanw** [comment]
Sorry! Found it in mcnSSD -- wasn't planning to use the data augmentation so didn't install in the beginning.

**Comment by albanie** [comment]
Ah, glad you found it! (sorry for the slow response)
