### ISSUE TITLE
Faster RCNN as text detector

### ISSUE THREAD

**Issue by wajahat57** [albanie/mcnFasterRCNN#2]
Hi 
Thanks a lot for sharing this code.
I want to use it for text detection.
For that purpose, I have text detector networks which I will use instead of VGG etc.

I want to know how plausible it is to use 32x32 character images split into character classes for training with a fixed training ROI bounding box of say 30x30 for every image?

Once trained, testing will be done on standard full size images (much bigger than 32x32 pixles).

Best Regards
Wajahat

**Comment by albanie** [comment]
I'm not too knowledgeable on text detection, but @ankush-me might have some ideas.
