### ISSUE TITLE
Anyone tried to run faster_rcnn_train.m?

### ISSUE THREAD

**Issue by daofeng2007** [albanie/mcnFasterRCNN#9]
faster_rcnn_train.m requires input of experiment folder and opts. It's difficult to guess what will be contained in opts; thus it's difficult to set up the opts. Additionally, it seems that the function for preparing the imdb data is not provided for training. If any one successfully run the faster_rcnn_train.m, please share us  with your code especially the parts dealing with the opts and imdb.
Thank you so much.

**Comment by wajahat57** [comment]
You will have to use pre-defined configurations for the datasets already configured, such as Pascal dataset training through faster_rcnn_pascal_train() in the pascal folder. This function will call faster_rcnn_train() after setting the opts.

**Comment by daofeng2007** [comment]
@wajahat57 Thanks a lot. I did not notice the existence of  this pascal folder. Now, I can run the training procedure!

**Comment by daofeng2007** [comment]
@wajahat57 
This training procedure has been running for almost half hour. What I got is seemingly endless dots.................................., as the attached pic shows. Is this the progressing bar for imdb or training, or am I doing something wrong?
![pascal](https://user-images.githubusercontent.com/11918249/36311914-d94db0fe-12fa-11e8-9186-1a43694f19ce.PNG)

**Comment by wajahat57** [comment]
for training you will get the losses displayed as:
`train: epoch 07: 1058/7450: 1.3 (1.4) Hz cls_error: 0.032 loss_bbox: 0.008 loss_cls: 0.145 multitask_loss: 0.153 rpn_loss_bbox: 0.001 rpn_loss_cls: 0.003`
This seems to be downloading something, maybe the dataset. Can't say anything for sure

**Comment by daofeng2007** [comment]
@wajahat57 Thank you. Now I get the same training progress status as provided by you. It turns out the dots are indication of data preparation progress like you said.
